name: Playwright CI

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

jobs:
  smoke_test:
    if: github.ref != 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright smoke tests
        run: npx playwright test --grep @smoke --reporter=allure-playwright

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 1

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}/${{ github.run_number }}/smoke

      - name: Post Allure report link
        if: always()
        run: |
          echo "### :rocket: [View Allure Smoke Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.ref_name }}/${{ github.run_number }}/smoke/)" >> $GITHUB_STEP_SUMMARY

  regression_test:
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'schedule'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright regression tests
        run: npx playwright test --grep @regression --reporter=allure-playwright

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 1

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}/${{ github.run_number }}/regression

      - name: Post Allure report link
        if: always()
        run: |
          echo "### :rocket: [View Allure Regression Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.ref_name }}/${{ github.run_number }}/regression/)" >> $GITHUB_STEP_SUMMARY

  api_test:
    if: github.event_name == 'push' || github.event_name == 'schedule'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright API tests
        run: npx playwright test --grep @apitests --reporter=allure-playwright

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 1

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}/${{ github.run_number }}/api

      - name: Post Allure report link
        if: always()
        run: |
          echo "### :rocket: [View Allure API Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.ref_name }}/${{ github.run_number }}/api/)" >> $GITHUB_STEP_SUMMARY